name: Build development infrastructure
on:
  push: 
    paths: 
      - infra/*
      - .github/workflows/infra-dev.yml
    branches-ignore:  
      - main

permissions:
      id-token: write
      contents: read
      
jobs: 
  deploy-dev:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: Deploy AKS cluster
          uses: azure/CLI@v1
          with:
            #azcliversion: 2.30.0
            inlineScript: |
              az stack group create -n cluster-dev \
              -g ${{ vars.RESOURCE_GROUP }} \
              --delete-resources \
              -p $GITHUB_WORKSPACE/infra/aks.bicepparam \
              --deny-settings-mode None

        - name: Set AKS context
          uses: azure/aks-set-context@v3
          with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}

        - name: Create namespaces
          uses: azure/k8s-deploy@v4
          with:
            namespace: 'default'
            manifests: |
              infra/manifests/namespaces.yml

        - name: Install NGINX ingress controller
          id: nginx-helm
          run: |
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helm repo update
            helm install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace dev