name: Build development infrastructure
on:
  push: 
    paths: 
      - infra/*
      - .github/workflows/infra-dev.yml
    branches-ignore:  
      - main

permissions:
      id-token: write
      contents: read
      
jobs: 
  deploy-dev:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: Deploy AKS cluster
          uses: azure/CLI@v1
          with:
            #azcliversion: 2.30.0
            inlineScript: |
              az stack group create -n cluster-dev \
              -g rg-tj-lotteri \
              --delete-resources \
              -p $GITHUB_WORKSPACE/infra/aks.bicepparam \
              -p environment=dev \
              --deny-settings-mode None
