name: Deploy development lotteriapp
on:
  push: 
    paths: 
      - lotteriapp/**
      - .github/workflows/lotteriapp-dev.yml
    branches-ignore:  
      - main

permissions:
      id-token: write
      contents: read
      actions: read
      
jobs: 
  deploy-lotteri-dev:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true
        
        - name: ACR login
          id: acr-login
          run: |
            az acr login --name lotteri

        - name: Build and push frontend
          id: build-image
          run: |
            az acr build --image lotteri.azurecr.io/frontend-dev:latest --registry lotteri --file "$GITHUB_WORKSPACE/lotteriapp/trekning-frontend/app/Dockerfile" .

        - name: Set AKS context
          uses: azure/aks-set-context@v3
          with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}

        - name: Update frontend deployment
          uses: azure/k8s-deploy@v4
          with:
            namespace: 'lotteri'
            manifests: |
              lotteriapp/manifests/frontend.yml
            images: 'lotteri.azurecr.io/frontend-dev:latest'